apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s01r7jlg3-go
  janus-idp.io/tekton: s01r7jlg3-go
  backstage.io/kubernetes-id: s01r7jlg3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s01r7jlg3-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
